### ISSUE TITLE
Different cache_aws_disable options for local vs ci

### ISSUE THREAD

**Issue by ddivecs** [bojanbass/nx-aws#362]
I need to set `NXCACHE_AWS_DISABLE=true` in a .env file and I see the codebase supports that. Every developer on the team is going to want to set this flag for local development, so we want to commit this to the repo. We then flip this using an env var in github actions for CI.

The .env file is also read by another tool for username/login tokens which I would like to not commit.

I currently cannot change where either of these .env files are read from, would it be possible to add API surface to allow passing a different path to a .env file in?

Alternatively, would it be possible to change/flip the nxcache_aws_disabled=true without a .env file?

**Comment by bojanbass** [comment]
I'm not sure I understood correctly the question, but if the issue is just to set env variables in a file and not commit it, you can simply use `.env.local` which should be added in `.gitignore`. The internal logic of NX looks for those files as well:
https://nx.dev/recipes/tips-n-tricks/define-environment-variables#setting-environment-variables

**Comment by bojanbass** [comment]
On the other side, I'm not sure if it's possible to pass this setting as an argument, because you always execute a specific nx task and arguments would automatically be passed into the task itself, not the runner.

**Comment by bojanbass** [comment]
If this is the case, we could change the logic inside this repo to support that. Would you want to prepare a PR?

**Comment by ddivecs** [comment]
@bojanbass  sorry this took a while to prepare, if you have any feedback or want to see any changes, please let me know
